### ISSUE TITLE
RedirectMissingLocation: Redirected but the response is missing a Location: header.

### ISSUE THREAD

**Issue by udithhaputhanthri** [RaviSoji/colab_utils#1]
`#!git clone https://github.com/RaviSoji/colab_utils.git  # Include the "!".

import colab_utils
drive = colab_utils.get_gdrive()

colab_utils.push_to_gdrive(drive,'celeba-dataset.zip', 'faces_celeba_dataset')

Error:
`---------------------------------------------------------------------------
RedirectMissingLocation                   Traceback (most recent call last)
<ipython-input-17-6d8191cf5c4d> in <module>()
      3 drive = colab_utils.get_gdrive()
      4 
----> 5 colab_utils.push_to_gdrive(drive,'celeba-dataset.zip', 'faces_celeba_dataset')
      6 #A=colab_utils.pull_from_gdrive(drive, 'GAN/img_original.pkl','NEWTEST.pkl')

11 frames
/usr/local/lib/python3.6/dist-packages/httplib2/__init__.py in _request(self, conn, host, absolute_uri, request_uri, method, body, headers, redirections, cachekey)
   1688                             ),
   1689                             response,
-> 1690                             content,
   1691                         )
   1692                     # Fix-up relative redirects (which violate an RFC 2616 MUST)

RedirectMissingLocation: Redirected but the response is missing a Location: header.`

Both directories are available in the colab and the drive

**Comment by RaviSoji** [comment]
Hey,

Sorry I have had no time to look at this between school, work, and the pandemic. If you managed to address the issue, feel free to make a pull request, and I will merge it.

Thanks!
Ravi B. Sojitra
